### ISSUE TITLE
[BUG] Incorrect indentantion when generating Movefile

### ISSUE THREAD

**Issue by zomars** [fabrica-wp/fabrica-dev-kit#23]
The local configuration added to the Movefile is rendering like this:
```
local:
  vhost: 'localhost:32770'
  wordpress_path: /Users/zomars/Sites/project/www
  database:
    port: '32768'
  name: wordpress
  user: wordpress
  password: wordpress
  host: 127.0.0.1
```
When is supposed to be rendering like this:
```
local:
  vhost: 'localhost:32770'
  wordpress_path: /Users/zomars/Sites/project/www
  database:
    port: '32768'
    name: wordpress
    user: wordpress
    password: wordpress
    host: 127.0.0.1
```
